sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: llback-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 1800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: true
  # jwt 密钥
  jwt-secret-key: ashiodaijkosncjkxziuxyiuxyzfbhiasdf
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
spring:
  redis:
    host: 120.27.201.34
    port: 6379
    password: zhao082020@
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.201.34:3306/llback?allowPublicKeyRetrieval=true
    username: ll
    password: O(i*U7y6
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
sa:
  public-key: 034331b158275b2867f12afc75051ebe56f38265469675a44c23563326df8fa63e
  private-key: fc3ff3f8dfff886dc34673a431ec562830b2933d720248e9f0a38aba38b0ab60
ftp:
  ip: 120.27.201.34
  port: 21
  user: ftpUser
  password: O(i*U7y6
  path: /home/ftpUser/cloudFile/

